In [ ]:
import numpy as np
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
import numpy as np
arr =np.array([5,-5,2.3,3,-2])
a=arr.sum()
print(a)

3.3


CREATING A NUMPY ARRAY

In [ ]:
#Aliasing
import numpy as np
a= [2,5,8,9]
numpy_array = np.array(a)
print(a)


#0-D array

import numpy as np
zero_array= np.array(1)
print(zero_array)
print("Dimension",zero_array.ndim)



[2, 5, 8, 9]
1
Dimension 0


In [ ]:
#code to find the dimension of defined array
print(numpy_array.ndim)
print(zero_array.ndim)

1
0


In [ ]:
#Creating a 2-d array
arr=[[1,2,3],[4,5,6]]
two_d_numpy_array=np.array(arr)
print(two_d_numpy_array.ndim)

2


In [ ]:
#Creating array and itsn attributes
a=[[2,4,6,8],[3,5,7,9]] #creating a list name 'a'
arr= np.array(a)         #converting the list imto numpy
print(arr)               #printing the array
print(arr.shape)         #printing a shape of array
print(arr.size)         #printing size of the array
print(arr.dtype)        #printing the datatype of elements inside the array


[[2 4 6 8]
 [3 5 7 9]]
(2, 4)
8
int64


ACCESSING NUMPY ARRAY INDEXES

In [ ]:
arr = np.array([3,5,7,9,11])
print(arr[0])
print(arr[2]+arr[4])

3
18


In [ ]:
arr2 =np.array([[1,3,3],[4,5,6]])
print(arr2)
print(arr2[1,1]-arr2[0,1])


[[1 3 3]
 [4 5 6]]
2


In [ ]:
arr_2d=np.array([[1,3,3,2],[4,7,6,7]])#here 0,1 means (1,3,3,2) positin 1 (look first  one i.e 0)
print(arr_2d[0,1])

arr_2d=np.array([[1,3,3,2],[4,7,6,7]])  #here 1,1 means (4,7,6,7) positin 1
print(arr_2d[1,1])

3
7


In [ ]:
arr3 =np.array([[[1,3,3],[4,5,6],[5,8,9]]])
print(arr3)
print(arr3[0,2,1])   #0 means whole matrix and 2 is 2nd row and 1 means postion 1 i.e (8)

print(arr3[0,2,1])  #for number 8

print(arr3[0,1,-2])



[[[1 3 3]
  [4 5 6]
  [5 8 9]]]
8
8
5


SLICING IN NUMPY_ARRAY

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5])                      #starting from 1 position or index and ending in 5 position (1:5 = 2,3,4,5)

print(arr[1:5:2])                     #starting from 1 position or index and ending in 5 position and jump from 2 (1:5:2 = 2,4)

[2 3 4 5]
[2 4]


In [ ]:
arr2 =np.array([[1,2,3],[4,5,6]])
# print (arr2)
print(arr2[0:1,1:2])


arr2 =np.array([[2,4,6,8,11],[1,3,5,7,9]])
# print (arr2)
print(arr2[1,0:3])

print(arr2[0,1:-2])



[[2]]
[1 3 5]
[4 6]


CLASSWORK

In [ ]:
#1
import numpy as np
arr=np.array([7,14,21,28])
print(arr)

[ 7 14 21 28]


In [ ]:
#2
arr2=np.array([[5,10,15],[20,25,30]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[ 5 10 15]
 [20 25 30]]
(2, 3)
2


In [ ]:
#3
arr3=np.zeros([2,3])
print(arr3)

arr4=np.arange(0,12,3)
print(arr4)


[[0. 0. 0.]
 [0. 0. 0.]]
[0 3 6 9]


In [ ]:
#4
arr5 =np.array([2,4,6,8])
print(arr5*3)

[ 6 12 18 24]


In [ ]:
#5
arr6 = np.array([1,3,5,7,9,11])
print(arr6)
print(arr6[2])
print(arr6[1:4])




[ 1  3  5  7  9 11]
5
[3 5 7]
