HANDS-ON-PRACTICELINEAR ALGEBRA FOR AI

EXERCISE 1: WORKING WITH SCALAR AND VECTORS

In [ ]:
import numpy as np
#creating a scalar
scalar = 7
print('scalar')
#creating a vector
vector = np.array([3,5,7])
print('Vector',vector)
#scalaing vector through a scalar aka.scalar vector
scaled_vector = scalar * vector
print('Scaled Vector',scaled_vector)



scalar
Vector [3 5 7]
Scaled Vector [21 35 49]


EXERCISE 2: VECTOR ADDITION AND SUBTRACTION

In [ ]:
import numpy as np
v1 = np.array([1,2,3])
v2 = np.array([3,4,5])
res = v1+v2
result = v1-v2
print('Addition is:',res)
print('Subtraction is:',result)


Addition is: [4 6 8]
Subtraction is: [-2 -2 -2]


EXERCISE 3: MATRIX CREATION AND BASIC OPERATION

In [ ]:
matrix1 = np.array([[2,4],[5,7]])
matrix2 = np.array([[6,8],[9,11]])

print(matrix1)
print(matrix2)

print(matrix1 + matrix2)
print(matrix1-matrix2)

[[2 4]
 [5 7]]
[[ 6  8]
 [ 9 11]]
[[ 8 12]
 [14 18]]
[[-4 -4]
 [-4 -4]]


Exercise 4:MATRIX MULTIPLICATION

In [ ]:
import numpy as np
matrix1= np.array([[1,2,3],[4,5,7],[0,8,6]]) #3*3 matrix code
matrix2 = np.array([[1,2,4],[3,1,2],[3,2,1]])
res = np.dot(matrix1,matrix2)
print(res)

[[16 10 11]
 [40 27 33]
 [42 20 22]]


In [ ]:
import numpy as np
m1 = np.array([[1,2],[2,3]]) #
res = np.dot(m1,m1)
print(res)

[[ 5  8]
 [ 8 13]]


In [ ]:
import numpy as np
m1 = np.array([[1,2],[2,4]])
m2 = np.array([[1,1],[2,2]])
a = (m1[0,0] * m2[0,0])+(m1[0,1] * m2[1,0])
b = (m1[0,0]* m2[0,1])+(m1[0,1]*m2[1,1])
c = (m1[1,0]*m2[0,0]) + (m1[1,1]*m2[1,0])
d = (m1[1,0]*m2[0,1])+ (m1[1,1]*m2[1,1])
print(a)
print(b)
print(c)
print(d)
result= np.dot(m1,m2)
print('the dot product is:',result)

5
5
10
10
the dot product is: [[ 5  5]
 [10 10]]


Exercise 5: Identity matrix and transpose

In [ ]:
import numpy as np
identity = np.eye(2)

print(identity)
#transpose
matrix = np.array([[1,2],[2,3]])
print(matrix.T)

a = m1[0,0],m1[1,0]
b= m1[0,1],m1[1,1]

print(a)
print(b)

[[1. 0.]
 [0. 1.]]
[[1 2]
 [2 3]]
(np.int64(1), np.int64(2))
(np.int64(2), np.int64(4))


Exercise 6: Matrix inverse



In [ ]:
import numpy as np

matrix1 = np.array([[2,4],[5,7]])
inverse = np.linalg.inv(matrix1)
mat_inv = np.dot(matrix1,inverse)
print(mat_inv)

[[1.0000000e+00 0.0000000e+00]
 [4.4408921e-16 1.0000000e+00]]
